//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("XRetailModel", "FK_AreasShops", "Areas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Area), "Shops", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.Shop), true)]
[assembly: EdmRelationshipAttribute("XRetailModel", "FK_CategoriesProducts", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Category), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.Product), true)]
[assembly: EdmRelationshipAttribute("XRetailModel", "FK_EmployeesVisits", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Employee), "Visits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.Visit), true)]
[assembly: EdmRelationshipAttribute("XRetailModel", "FK_OrdersEmployees", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Employee), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.Order), true)]
[assembly: EdmRelationshipAttribute("XRetailModel", "FK_OrdersOrderDetails", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Order), "OrderDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.OrderDetail), true)]
[assembly: EdmRelationshipAttribute("XRetailModel", "FK_ProductsOrderDetails", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Product), "OrderDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.OrderDetail), true)]
[assembly: EdmRelationshipAttribute("XRetailModel", "FK_OrdersShops", "Shops", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.Shop), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.Order), true)]

#endregion

namespace BusinessObjects
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class XRetailEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new XRetailEntities object using the connection string found in the 'XRetailEntities' section of the application configuration file.
        /// </summary>
        public XRetailEntities() : base("name=XRetailEntities", "XRetailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XRetailEntities object.
        /// </summary>
        public XRetailEntities(string connectionString) : base(connectionString, "XRetailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XRetailEntities object.
        /// </summary>
        public XRetailEntities(EntityConnection connection) : base(connection, "XRetailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Area> Areas
        {
            get
            {
                if ((_Areas == null))
                {
                    _Areas = base.CreateObjectSet<Area>("Areas");
                }
                return _Areas;
            }
        }
        private ObjectSet<Area> _Areas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderDetail> OrderDetails
        {
            get
            {
                if ((_OrderDetails == null))
                {
                    _OrderDetails = base.CreateObjectSet<OrderDetail>("OrderDetails");
                }
                return _OrderDetails;
            }
        }
        private ObjectSet<OrderDetail> _OrderDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shop> Shops
        {
            get
            {
                if ((_Shops == null))
                {
                    _Shops = base.CreateObjectSet<Shop>("Shops");
                }
                return _Shops;
            }
        }
        private ObjectSet<Shop> _Shops;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Visit> Visits
        {
            get
            {
                if ((_Visits == null))
                {
                    _Visits = base.CreateObjectSet<Visit>("Visits");
                }
                return _Visits;
            }
        }
        private ObjectSet<Visit> _Visits;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Areas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAreas(Area area)
        {
            base.AddObject("Areas", area);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderDetails(OrderDetail orderDetail)
        {
            base.AddObject("OrderDetails", orderDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shops EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShops(Shop shop)
        {
            base.AddObject("Shops", shop);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Visits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisits(Visit visit)
        {
            base.AddObject("Visits", visit);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Area : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Area object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Area CreateArea(global::System.Int32 id, global::System.String name)
        {
            Area area = new Area();
            area.Id = id;
            area.name = name;
            return area;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_AreasShops", "Shops")]
        public EntityCollection<Shop> Shops
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shop>("XRetailModel.FK_AreasShops", "Shops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shop>("XRetailModel.FK_AreasShops", "Shops", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Category CreateCategory(global::System.Int32 id, global::System.String name)
        {
            Category category = new Category();
            category.Id = id;
            category.name = name;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_CategoriesProducts", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("XRetailModel.FK_CategoriesProducts", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("XRetailModel.FK_CategoriesProducts", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Employee CreateEmployee(global::System.Int32 id, global::System.String name)
        {
            Employee employee = new Employee();
            employee.Id = id;
            employee.name = name;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_EmployeesVisits", "Visits")]
        public EntityCollection<Visit> Visits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Visit>("XRetailModel.FK_EmployeesVisits", "Visits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Visit>("XRetailModel.FK_EmployeesVisits", "Visits", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_OrdersEmployees", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("XRetailModel.FK_OrdersEmployees", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("XRetailModel.FK_OrdersEmployees", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="orderDate">Initial value of the orderDate property.</param>
        /// <param name="requiredDate">Initial value of the requiredDate property.</param>
        /// <param name="employees_Id">Initial value of the Employees_Id property.</param>
        /// <param name="shops_Id">Initial value of the Shops_Id property.</param>
        public static Order CreateOrder(global::System.Int32 id, global::System.DateTime orderDate, global::System.DateTime requiredDate, global::System.Int32 employees_Id, global::System.Int32 shops_Id)
        {
            Order order = new Order();
            order.Id = id;
            order.orderDate = orderDate;
            order.requiredDate = requiredDate;
            order.Employees_Id = employees_Id;
            order.Shops_Id = shops_Id;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime orderDate
        {
            get
            {
                return _orderDate;
            }
            set
            {
                OnorderDateChanging(value);
                ReportPropertyChanging("orderDate");
                _orderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDate");
                OnorderDateChanged();
            }
        }
        private global::System.DateTime _orderDate;
        partial void OnorderDateChanging(global::System.DateTime value);
        partial void OnorderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime requiredDate
        {
            get
            {
                return _requiredDate;
            }
            set
            {
                OnrequiredDateChanging(value);
                ReportPropertyChanging("requiredDate");
                _requiredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("requiredDate");
                OnrequiredDateChanged();
            }
        }
        private global::System.DateTime _requiredDate;
        partial void OnrequiredDateChanging(global::System.DateTime value);
        partial void OnrequiredDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> shippedDate
        {
            get
            {
                return _shippedDate;
            }
            set
            {
                OnshippedDateChanging(value);
                ReportPropertyChanging("shippedDate");
                _shippedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shippedDate");
                OnshippedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _shippedDate;
        partial void OnshippedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnshippedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Employees_Id
        {
            get
            {
                return _Employees_Id;
            }
            set
            {
                OnEmployees_IdChanging(value);
                ReportPropertyChanging("Employees_Id");
                _Employees_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Employees_Id");
                OnEmployees_IdChanged();
            }
        }
        private global::System.Int32 _Employees_Id;
        partial void OnEmployees_IdChanging(global::System.Int32 value);
        partial void OnEmployees_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Shops_Id
        {
            get
            {
                return _Shops_Id;
            }
            set
            {
                OnShops_IdChanging(value);
                ReportPropertyChanging("Shops_Id");
                _Shops_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shops_Id");
                OnShops_IdChanged();
            }
        }
        private global::System.Int32 _Shops_Id;
        partial void OnShops_IdChanging(global::System.Int32 value);
        partial void OnShops_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_OrdersEmployees", "Employees")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("XRetailModel.FK_OrdersEmployees", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("XRetailModel.FK_OrdersEmployees", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("XRetailModel.FK_OrdersEmployees", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("XRetailModel.FK_OrdersEmployees", "Employees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_OrdersOrderDetails", "OrderDetails")]
        public EntityCollection<OrderDetail> OrderDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderDetail>("XRetailModel.FK_OrdersOrderDetails", "OrderDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderDetail>("XRetailModel.FK_OrdersOrderDetails", "OrderDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_OrdersShops", "Shops")]
        public Shop Shop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shop>("XRetailModel.FK_OrdersShops", "Shops").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shop>("XRetailModel.FK_OrdersShops", "Shops").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shop> ShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shop>("XRetailModel.FK_OrdersShops", "Shops");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shop>("XRetailModel.FK_OrdersShops", "Shops", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="OrderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="property">Initial value of the Property property.</param>
        /// <param name="unitPrice">Initial value of the unitPrice property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        /// <param name="discount">Initial value of the discount property.</param>
        /// <param name="order_Id">Initial value of the Order_Id property.</param>
        /// <param name="product_Id">Initial value of the Product_Id property.</param>
        public static OrderDetail CreateOrderDetail(global::System.Int32 id, global::System.String property, global::System.String unitPrice, global::System.String quantity, global::System.String discount, global::System.Int32 order_Id, global::System.Int32 product_Id)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.Id = id;
            orderDetail.Property = property;
            orderDetail.unitPrice = unitPrice;
            orderDetail.quantity = quantity;
            orderDetail.discount = discount;
            orderDetail.Order_Id = order_Id;
            orderDetail.Product_Id = product_Id;
            return orderDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property
        {
            get
            {
                return _Property;
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.String _Property;
        partial void OnPropertyChanging(global::System.String value);
        partial void OnPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unitPrice
        {
            get
            {
                return _unitPrice;
            }
            set
            {
                OnunitPriceChanging(value);
                ReportPropertyChanging("unitPrice");
                _unitPrice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unitPrice");
                OnunitPriceChanged();
            }
        }
        private global::System.String _unitPrice;
        partial void OnunitPriceChanging(global::System.String value);
        partial void OnunitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.String _quantity;
        partial void OnquantityChanging(global::System.String value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String discount
        {
            get
            {
                return _discount;
            }
            set
            {
                OndiscountChanging(value);
                ReportPropertyChanging("discount");
                _discount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("discount");
                OndiscountChanged();
            }
        }
        private global::System.String _discount;
        partial void OndiscountChanging(global::System.String value);
        partial void OndiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order_Id
        {
            get
            {
                return _Order_Id;
            }
            set
            {
                OnOrder_IdChanging(value);
                ReportPropertyChanging("Order_Id");
                _Order_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order_Id");
                OnOrder_IdChanged();
            }
        }
        private global::System.Int32 _Order_Id;
        partial void OnOrder_IdChanging(global::System.Int32 value);
        partial void OnOrder_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Id
        {
            get
            {
                return _Product_Id;
            }
            set
            {
                OnProduct_IdChanging(value);
                ReportPropertyChanging("Product_Id");
                _Product_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_Id");
                OnProduct_IdChanged();
            }
        }
        private global::System.Int32 _Product_Id;
        partial void OnProduct_IdChanging(global::System.Int32 value);
        partial void OnProduct_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_OrdersOrderDetails", "Orders")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("XRetailModel.FK_OrdersOrderDetails", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("XRetailModel.FK_OrdersOrderDetails", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("XRetailModel.FK_OrdersOrderDetails", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("XRetailModel.FK_OrdersOrderDetails", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_ProductsOrderDetails", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("XRetailModel.FK_ProductsOrderDetails", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("XRetailModel.FK_ProductsOrderDetails", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("XRetailModel.FK_ProductsOrderDetails", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("XRetailModel.FK_ProductsOrderDetails", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="quantityPerUnit">Initial value of the quantityPerUnit property.</param>
        /// <param name="unitPrice">Initial value of the unitPrice property.</param>
        /// <param name="unitsInStock">Initial value of the unitsInStock property.</param>
        /// <param name="unitsOnOrder">Initial value of the unitsOnOrder property.</param>
        /// <param name="discontinued">Initial value of the discontinued property.</param>
        /// <param name="category_Id">Initial value of the Category_Id property.</param>
        public static Product CreateProduct(global::System.Int32 id, global::System.String name, global::System.Int32 quantityPerUnit, global::System.Int32 unitPrice, global::System.Int32 unitsInStock, global::System.Int32 unitsOnOrder, global::System.Boolean discontinued, global::System.Int32 category_Id)
        {
            Product product = new Product();
            product.Id = id;
            product.name = name;
            product.quantityPerUnit = quantityPerUnit;
            product.unitPrice = unitPrice;
            product.unitsInStock = unitsInStock;
            product.unitsOnOrder = unitsOnOrder;
            product.discontinued = discontinued;
            product.Category_Id = category_Id;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 quantityPerUnit
        {
            get
            {
                return _quantityPerUnit;
            }
            set
            {
                OnquantityPerUnitChanging(value);
                ReportPropertyChanging("quantityPerUnit");
                _quantityPerUnit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantityPerUnit");
                OnquantityPerUnitChanged();
            }
        }
        private global::System.Int32 _quantityPerUnit;
        partial void OnquantityPerUnitChanging(global::System.Int32 value);
        partial void OnquantityPerUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 unitPrice
        {
            get
            {
                return _unitPrice;
            }
            set
            {
                OnunitPriceChanging(value);
                ReportPropertyChanging("unitPrice");
                _unitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unitPrice");
                OnunitPriceChanged();
            }
        }
        private global::System.Int32 _unitPrice;
        partial void OnunitPriceChanging(global::System.Int32 value);
        partial void OnunitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 unitsInStock
        {
            get
            {
                return _unitsInStock;
            }
            set
            {
                OnunitsInStockChanging(value);
                ReportPropertyChanging("unitsInStock");
                _unitsInStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unitsInStock");
                OnunitsInStockChanged();
            }
        }
        private global::System.Int32 _unitsInStock;
        partial void OnunitsInStockChanging(global::System.Int32 value);
        partial void OnunitsInStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 unitsOnOrder
        {
            get
            {
                return _unitsOnOrder;
            }
            set
            {
                OnunitsOnOrderChanging(value);
                ReportPropertyChanging("unitsOnOrder");
                _unitsOnOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unitsOnOrder");
                OnunitsOnOrderChanged();
            }
        }
        private global::System.Int32 _unitsOnOrder;
        partial void OnunitsOnOrderChanging(global::System.Int32 value);
        partial void OnunitsOnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean discontinued
        {
            get
            {
                return _discontinued;
            }
            set
            {
                OndiscontinuedChanging(value);
                ReportPropertyChanging("discontinued");
                _discontinued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("discontinued");
                OndiscontinuedChanged();
            }
        }
        private global::System.Boolean _discontinued;
        partial void OndiscontinuedChanging(global::System.Boolean value);
        partial void OndiscontinuedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Category_Id
        {
            get
            {
                return _Category_Id;
            }
            set
            {
                OnCategory_IdChanging(value);
                ReportPropertyChanging("Category_Id");
                _Category_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category_Id");
                OnCategory_IdChanged();
            }
        }
        private global::System.Int32 _Category_Id;
        partial void OnCategory_IdChanging(global::System.Int32 value);
        partial void OnCategory_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_CategoriesProducts", "Categories")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("XRetailModel.FK_CategoriesProducts", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("XRetailModel.FK_CategoriesProducts", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("XRetailModel.FK_CategoriesProducts", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("XRetailModel.FK_CategoriesProducts", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_ProductsOrderDetails", "OrderDetails")]
        public EntityCollection<OrderDetail> OrderDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderDetail>("XRetailModel.FK_ProductsOrderDetails", "OrderDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderDetail>("XRetailModel.FK_ProductsOrderDetails", "OrderDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Shop")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shop : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shop object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="owner">Initial value of the owner property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="lastShippingDate">Initial value of the lastShippingDate property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="area_Id">Initial value of the Area_Id property.</param>
        public static Shop CreateShop(global::System.Int32 id, global::System.String owner, global::System.String address, global::System.String phone, global::System.DateTime lastShippingDate, global::System.String name, global::System.Int32 area_Id)
        {
            Shop shop = new Shop();
            shop.Id = id;
            shop.owner = owner;
            shop.address = address;
            shop.phone = phone;
            shop.lastShippingDate = lastShippingDate;
            shop.name = name;
            shop.Area_Id = area_Id;
            return shop;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.String _owner;
        partial void OnownerChanging(global::System.String value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> productivityIndex
        {
            get
            {
                return _productivityIndex;
            }
            set
            {
                OnproductivityIndexChanging(value);
                ReportPropertyChanging("productivityIndex");
                _productivityIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productivityIndex");
                OnproductivityIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _productivityIndex;
        partial void OnproductivityIndexChanging(Nullable<global::System.Int32> value);
        partial void OnproductivityIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastShippingDate
        {
            get
            {
                return _lastShippingDate;
            }
            set
            {
                OnlastShippingDateChanging(value);
                ReportPropertyChanging("lastShippingDate");
                _lastShippingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastShippingDate");
                OnlastShippingDateChanged();
            }
        }
        private global::System.DateTime _lastShippingDate;
        partial void OnlastShippingDateChanging(global::System.DateTime value);
        partial void OnlastShippingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Area_Id
        {
            get
            {
                return _Area_Id;
            }
            set
            {
                OnArea_IdChanging(value);
                ReportPropertyChanging("Area_Id");
                _Area_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Area_Id");
                OnArea_IdChanged();
            }
        }
        private global::System.Int32 _Area_Id;
        partial void OnArea_IdChanging(global::System.Int32 value);
        partial void OnArea_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_AreasShops", "Areas")]
        public Area Area
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("XRetailModel.FK_AreasShops", "Areas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("XRetailModel.FK_AreasShops", "Areas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Area> AreaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("XRetailModel.FK_AreasShops", "Areas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Area>("XRetailModel.FK_AreasShops", "Areas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_OrdersShops", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("XRetailModel.FK_OrdersShops", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("XRetailModel.FK_OrdersShops", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XRetailModel", Name="Visit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Visit object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="views">Initial value of the views property.</param>
        /// <param name="employee_Id">Initial value of the Employee_Id property.</param>
        public static Visit CreateVisit(global::System.Int32 id, global::System.String views, global::System.Int32 employee_Id)
        {
            Visit visit = new Visit();
            visit.Id = id;
            visit.views = views;
            visit.Employee_Id = employee_Id;
            return visit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String views
        {
            get
            {
                return _views;
            }
            set
            {
                OnviewsChanging(value);
                ReportPropertyChanging("views");
                _views = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("views");
                OnviewsChanged();
            }
        }
        private global::System.String _views;
        partial void OnviewsChanging(global::System.String value);
        partial void OnviewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Employee_Id
        {
            get
            {
                return _Employee_Id;
            }
            set
            {
                OnEmployee_IdChanging(value);
                ReportPropertyChanging("Employee_Id");
                _Employee_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Employee_Id");
                OnEmployee_IdChanged();
            }
        }
        private global::System.Int32 _Employee_Id;
        partial void OnEmployee_IdChanging(global::System.Int32 value);
        partial void OnEmployee_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XRetailModel", "FK_EmployeesVisits", "Employees")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("XRetailModel.FK_EmployeesVisits", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("XRetailModel.FK_EmployeesVisits", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("XRetailModel.FK_EmployeesVisits", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("XRetailModel.FK_EmployeesVisits", "Employees", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
